name: pit_stop
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  google_fonts:
  flutter_riverpod:

  carousel_slider:
  provider:
  fluttertoast:
  flutter_svg:
  flutter_spinkit:
  circle_nav_bar:
  flutter_secure_storage:

  image_picker:
  table_calendar:
  country_pickers:
  easy_stepper:
  cached_network_image:
  intl:
  shimmer:
  file_picker:
  dio:
  pinput:
  dotted_border:
  flutter_dotenv:
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  animated_notch_bottom_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
